PKGBUILD: after installation, say we can run the client exec'ing "desura".
PKGBUILD: actually add .install file...

PKGBUILD: if  ./build_cmake_clean.sh fails, run git clean -dfx.

PKGBUILD: make failure of getceflibs.sh fatal (currently commented out).

diff --git a/distro/archlinux/PKGBUILD b/distro/archlinux/PKGBUILD
--- a/distro/archlinux/PKGBUILD
+++ b/distro/archlinux/PKGBUILD
@@ -1,7 +1,7 @@
 # Creator: Sven-Hendrik Haase <sh@lutzhaase.com>
 # Maintainer: Jookia <166291@gmail.com>
 pkgname=desurium-git
-pkgver=20120407
+pkgver=20120408
 pkgrel=1
 pkgdesc="A community-driven digital distribution service for gamers (open source version)"
 url="http://github.com/lodle/Desurium"
@@ -14,8 +14,11 @@ depends=('v8' 'tinyxml' 'sqlite' 'boost-libs' 'bzip2' 'gtk2' 'openssl'
          'gconf' 'xdg-user-dirs' 'v8')
 provides=('desura')
 conflicts=('desura')
-source=('run-desura.sh')
-sha1sums=('2b42eaf7ce9ca41fa3c340c2b2ea147806025b8b')
+install=desurium-git.install
+source=('run-desura.sh'
+        'desurium-git.install')
+sha1sums=('2b42eaf7ce9ca41fa3c340c2b2ea147806025b8b'
+          '5bc0f47b75bb328b2bb3a735a55558edce75f741')
 
 _gitroot=git://github.com/lodle/Desurium.git
 _gitname=Desurium
@@ -27,7 +30,8 @@ build() {
   if [[ -d "$_gitname" ]]; then
     cd "$_gitname"
     msg "Removing build files..."
-    ./build_make_clean.sh
+    # if this fails, git clean -dfx
+    ./build_make_clean.sh || echo "./build_make_clean.sh failed, runnung  git clean -dfx ..." ; git clean -dfx
     msg "Updating..."
     git pull origin
     msg "The local files are updated."
@@ -52,6 +56,7 @@ build() {
   cd ..
   msg "Running getceflibs.sh ..."
   ./getceflibs.sh /opt/desura
+#  ./getceflibs.sh /opt/desura  || echo "getceflibs.sh failed." ; false
 }
 
 package() {
